server:
  port: 8091


spring:
  profiles:
    active: "@profileName@"
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:conf/fl.db
    username:
    password:
caffeinecache:
  timeToLive: 1800
  maxSize: 500

jdchain:
  available: false
  gateway_ip: "116.196.65.147" #连接网关服务IP
  gateway_port: "32002" #连接网关服务端口
  gateway_secure: "false" #网关服务是否开启tls(false:不支持 true:支持),目前暂不支持tls
  user_pubkey: "7VeRFJPfnoWksyxKLUY7qK7XP8xD8EZ9aiNfHfdM4ey23S1B" #用户公钥
  user_privkey: "177gjxruAYxLjJYKcxr8RKdxxwgwLFQkA1XJn1GhD7jy7pWKhsVEJzcApiyPXYHfF2XoKXD" #用户私钥
  user_privpwd: "Eiv754Xr94AEJLUfZBRtBYpRy6Sr1H5eJxwLVcgcuAp7" #解密私钥密码
  ledger_address: "j5gFEARk5HszKioMZvaKeH5uyugLiHamYK7Ln5AhTn9dzy" #账本Hash,用于多账本时配置，如果仅有一个账本，可不配置
  contract_address: "LdeNw2zhKoUPBZZkWBVNo6fvgfHYkotqaRk6z" #合约地址
  data_account_address: "LdeNf8bTBkBcRM4b8MjbS6ZqMZeRsELSai5rk" #数据账户地址
  event_account_address: "LdeNiXDTQnUdfuSR5cfae46kPT8qdFaxxytc4" #事件账户地址
  user_table_address: "LdeNv9t9PThwZLbi7Gwr6kiSSzJ7YGguvNm18" #user信息的数据账户地址
  task_table_address: "LdeNzTE8apA4DcWYsydcAPFk6xYMsaB1g8SG2" #task信息的数据账户地址
  train_table_address: "LdeNmJWFnMrbm5SFJEti9Grxik52RPeqKA3UV" #train信息的数据账户地址
  merchant_table_address: "LdeNks5eGeyXimW27MXryHRFLBPzhAT2xz2kD" #merchant数据账户地址
  default_user: "admin" #默认的用户名
  default_password: "666666" #默认用户的密码

